baseURL: "https://hugo-profile.netlify.app"
languageCode: "fr-fr"
title: "Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
 # main:
    #- identifier: blog
     # name: Blog
      #title: Blog posts
     # url: /blogs
     # weight: 1
    #- identifier: gallery
      #name: Gallery
      #title: Blog posts
      #url: /gallery
      #weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: ""

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: falsesss
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
#  color:
#    textColor: 
#    secondaryTextColor:
#    backgroundColor: 
#    secondaryBackgroundColor:
#    primaryColor:
#    secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    center: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
   # intro: "Bonjour! Je suis "
    title: "Alban Le Rouzic"
    subtitle: "Ingénieur en Informatique"
    content: "Passionné par les sciences du numérique, j’ai entrepris un cursus orienté génie logiciel dès mon entrée en école d’ingénieur. Mon envie de mettre à profit et de rendre concret mes compétences dans ce domaine, m'a conduit à poursuivre mes études en école d’ingénieur par la filière en alternance."
    image: /images/hero.jpg
    button:
      enable: true
      name: "CV"
      url: "https://portfolio-alban-lr.netlify.app/images/cv.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        # - icon: fab fa-github
        #   url: https://example.com
        # - icon: fab fa-twitter
        #   url: https://example.com
      customIcons:
        # - icon: /fav.png
        #   url: "https://example.com"

  # About
  about:
    enable: true
    title: "Compétences"
    image: "/images/test.jpeg"
    content: |-
      I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experiences
  experience:
    enable: true
    title: "Expériences"
    items:
      - job: "Développeur Full-stack"
        company: "Marine Nationale - CECLANT"
        companyUrl: "https://www.premar-atlantique.gouv.fr/"
        date: "Novembre 2020 - fin prévue pour Septembre 2023"
        content: |
          Alternance au sein du Laboratoire Numérique de l'amirauté de Brest. 

          - Réunions, échanges et rédaction du cahier des charges de concert avec les clients.
          - Gestion et suivi de projets. Préparation des réunions clients, des comptes rendus des réunions, mise au point sur les avancées et modifications à venir sur les projets.
          - Conceptualisation du design, de l'architecture, de la base de donées, des maquettes des outils.
          - Développement web des outils (javascript/w2ui | Html/CSS | PHP | SQL).
          - Délivrance des projets/ suivis de ceux ci auprès des clients afin d'assurer le MCO (Maintien en Condition Opérationnel) des outils.

      - job: "Soutien logisitique"
        company: "CIC Banque Privée"
        companyUrl: "https://www.cic.fr/banqueprivee/fr/"
        date: "Juillet 2019 - Août 2019"
        content: |
          Intervention et soutien logistique aux équipes du CIC Banque Privée de Brest.
            - Récupération et réponse aux appels des clients en adéquation de leur demandes. 

      - job: "Intervenant"
        company: "CLIP"
        companyUrl: "https://assoclip.fr/"
        date: "Août 2018 "
        content: | 
          Intervenant pour le CLIP (Club informatique pénitentiaire) à la Maison d'arrêt de Brest.

            - Gestion de groupes d'une dizaine de personnes.
            - Enseignement des logiciels de bureautiques (word, excel...), des bases de l'informatiques.
            - Soutien sur CV et lettres de motivations dans le cadre la réinsertion des détenus.
          

  

  # Education
  education:
    enable: true
    title: "Formations"
    index: false
    items:
      - title: "Diplôme d'Ingénieur Par Apprentissage"
        school: 
          name: "Institut Supérieur de l'Electronique et du Numérique, Brest"
          url: "https://isen-brest.fr/"
        date: "2020 - 2023"
        content: |-
          Après la période COVID et les différents confinements, j'ai ressenti le besoin de poursuivre mes études dans du concret. C'est pourquoi j'ai changé de cursus au sein de l'ISEN afin de faire mon diplôme d'ingénieur en alternance.

      - title: "Classe préparatoire intégré Cycle Informatique et Réseau"
        school: 
          name: "Institut Supérieur de l'Electronique et du Numérique, Brest"
          url: "https://isen-brest.fr/"
        date: "2017 - 2020"
        content: |-
          Début d'études au sein de l'ISEN de Brest et de son cursus classe préparatoire dans le Cycle Informatique et Réseau

      - title: "Baccalauréat option Informatique et Science du Numérique "
        school:
          name: "Lycée de l'Harteloire, Brest"
        date : "2017"


  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:

      - title: TOEIC (Test Of English for International Communication)                              
        content: 2022 - 990/990
        image: /images/certifications/toeic.jpeg

      - title: FCE (First Certificate in English of Cambridge) 
        content: 2017 - Grade B
        image: /images/certifications/fce.jpeg


  # projects
  projects:
    enable: false
    title: "Projets"
    items: 
      - title: Application android de scan et d'identification d'alergènes | site web pour la gestion des abonnés au service  
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        id : radish
        image: /images/projects/dish.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Flutter"
          - "Spring"
          - "Vue.js"
          - "Apicurio"
          - "Firebase"

      - title: HydroMétéo
        content: Un panneau LED qui affiche les données météo et hydrographique en fonction de la localité souhaitée
        id : hydro
        image: /images/projects/hydro.png
        badges:
          - "Python"
          - "Raspberry Pi"
          - "AdaFruit"

      - title: Star Wars Tic Tac Toe
        id : tictac
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/sw.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Android Studio"
          - "Firebase"
        links:
          - icon: fab fa-github
            url: https://github.com/ALbanLR/MORISEN_HTA_ALR

      - title: Site pour une personne en reconversion
        id : site
        content: Mise en place d'un site Wordpress et de ses bases, accompagnement de la personne dans l'outil pour assurer son autonomie dans la création et modification de contenus
        image: /images/projects/st.png
        featured:
          name: Lien
          link: http://reikinatur.com/
        badges:
          - "Wordpress"

      - title: Pong
        id : pong
        content: Un jeu pong en C++ et en Qt
        image: /images/projects/pong.png
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "C++"
          - "Qt"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

      - title: Robot Pompier
        id : pompier
        content: un truc
        image: /images/projects/rb.png
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "C"
          - "C++"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2



  #Contact
  contact:
    enable: true
    title: "Contact"
    content: Si vous souhaitez me contacter, je suis joignable par mail!
    email: alrouzic@gmail.com
    btnName: Me contacter

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: true
    socialNetworks:

      linkedin: https://linkedin.com


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
